name: Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: npm Install
        working-directory: ./NodeGoat
        run: npm install

      - name: Install SonarScanner
        run: npm install -g sonar-scanner

      - name: Run SonarScanner
        working-directory: ./NodeGoat
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=sast-dast-project \
            -Dsonar.projectKey=Toluowo_SAST_DAST_Project \
            -Dsonar.projectName=SAST_DAST_Project \
            -Dsonar.branch.name=main \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  dast:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build NodeGoat Docker image
        run: |
          docker build -t custom-nodegoat ./NodeGoat

      - name: Create Docker network
        run: docker network create zap-net || true

      - name: Run NodeGoat container
        run: |
          docker run -d --rm --name nodegoat --network zap-net -p 4000:4000 custom-nodegoat

      - name: Wait for NodeGoat to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4000 >/dev/null; then
              echo 'NodeGoat is up!'
              break
            fi
            echo "Waiting for NodeGoat..."
            sleep 2
          done

      - name: Run ZAP Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run --rm --network zap-net -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://nodegoat:4000 -r zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html

